export const FETCH_MOVIES_START = "FETCH_MOVIES_START";
export const FETCH_MOVIES_END = "FETCH_MOVIES_END";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_ERROR = "FETCH_MOVIES_ERROR";
export const CLEAR_MOVIES = "CLEAR_MOVIES";
